name: service-provider-system
services:
    postgres:
        container_name: postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            -   ./postgres/data:/var/lib/postgresql/data
        image: postgres

    pgadmin4:
        container_name: pgadmin4
        ports:
            - 8081:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        image: dpage/pgadmin4
        depends_on:
            - postgres